title: Minghan's Homepage
page-top-title: Minghan Wei
top-section-bg-text: Be what you wanna be
home-subtitle: Minghan Wei&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Minghan Wei 2023-2025. All Rights Reserved.'
