title: Minghan Wei | Personal Website
page-top-title: Minghan Wei
top-section-bg-text: Welcome to my personal website
about-subtitle: Minghan Wei&ensp;|&ensp;魏明涵
copyright-text: '&copy; Minghan Wei 2023-2026. All Rights Reserved.'
